export const THEMES = [
  {
    name: "light",
    label: "Light",
    colors: ["#ffffff", "#5a67d8", "#8b5cf6", "#1a202c"],
  },
  {
    name: "dark",
    label: "Dark",
    colors: ["#1f2937", "#8b5cf6", "#ec4899", "#1a202c"],
  },
  {
    name: "cupcake",
    label: "Cupcake",
    colors: ["#f5f5f4", "#65c3c8", "#ef9fbc", "#291334"],
  },
  {
    name: "forest",
    label: "Forest",
    colors: ["#1f1d1d", "#3ebc96", "#70c217", "#e2e8f0"],
  },
  {
    name: "bumblebee",
    label: "Bumblebee",
    colors: ["#ffffff", "#f8e36f", "#f0d50c", "#1c1917"],
  },
  {
    name: "emerald",
    label: "Emerald",
    colors: ["#ffffff", "#66cc8a", "#3b82f6", "#1e3a8a"],
  },
  {
    name: "corporate",
    label: "Corporate",
    colors: ["#ffffff", "#4b6bfb", "#7b92b2", "#1d232a"],
  },
  {
    name: "synthwave",
    label: "Synthwave",
    colors: ["#2d1b69", "#e779c1", "#58c7f3", "#f8f8f2"],
  },
  {
    name: "retro",
    label: "Retro",
    colors: ["#e4d8b4", "#ea6962", "#6aaa64", "#282425"],
  },
  {
    name: "cyberpunk",
    label: "Cyberpunk",
    colors: ["#ffee00", "#ff7598", "#75d1f0", "#1a103d"],
  },
  {
    name: "valentine",
    label: "Valentine",
    colors: ["#f0d6e8", "#e96d7b", "#a991f7", "#37243c"],
  },
  {
    name: "halloween",
    label: "Halloween",
    colors: ["#0d0d0d", "#ff7800", "#006400", "#ffffff"],
  },
  {
    name: "garden",
    label: "Garden",
    colors: ["#e9e7e7", "#ec4899", "#16a34a", "#374151"],
  },

  {
    name: "aqua",
    label: "Aqua",
    colors: ["#193549", "#4cd4e3", "#9059ff", "#f8d766"],
  },
  {
    name: "lofi",
    label: "Lofi",
    colors: ["#0f0f0f", "#1a1919", "#232323", "#2c2c2c"],
  },
  {
    name: "pastel",
    label: "Pastel",
    colors: ["#f7f3f5", "#d1c1d7", "#a1e3d8", "#4a98f1"],
  },
  {
    name: "fantasy",
    label: "Fantasy",
    colors: ["#ffe7d6", "#a21caf", "#3b82f6", "#f59e0b"],
  },
  {
    name: "wireframe",
    label: "Wireframe",
    colors: ["#e6e6e6", "#b3b3b3", "#b3b3b3", "#888888"],
  },
  {
    name: "black",
    label: "Black",
    colors: ["#000000", "#191919", "#313131", "#4a4a4a"],
  },
  {
    name: "luxury",
    label: "Luxury",
    colors: ["#171618", "#1e293b", "#94589c", "#d4a85a"],
  },
  {
    name: "dracula",
    label: "Dracula",
    colors: ["#282a36", "#ff79c6", "#bd93f9", "#f8f8f2"],
  },
  {
    name: "cmyk",
    label: "CMYK",
    colors: ["#f0f0f0", "#0891b2", "#ec4899", "#facc15"],
  },
  {
    name: "autumn",
    label: "Autumn",
    colors: ["#f2f2f2", "#8c1f11", "#f28c18", "#6f4930"],
  },
  {
    name: "business",
    label: "Business",
    colors: ["#f5f5f5", "#1e40af", "#3b82f6", "#f97316"],
  },
  {
    name: "acid",
    label: "Acid",
    colors: ["#110e0e", "#ff00f2", "#ff7a00", "#99ff01"],
  },
  {
    name: "lemonade",
    label: "Lemonade",
    colors: ["#ffffff", "#67e8f9", "#f5d742", "#2c3333"],
  },
  {
    name: "night",
    label: "Night",
    colors: ["#0f172a", "#38bdf8", "#818cf8", "#e2e8f0"],
  },
  {
    name: "coffee",
    label: "Coffee",
    colors: ["#20161f", "#dd9866", "#497174", "#eeeeee"],
  },
  {
    name: "winter",
    label: "Winter",
    colors: ["#ffffff", "#0284c7", "#d946ef", "#0f172a"],
  },
  {
    name: "dim",
    label: "Dim",
    colors: ["#1c1c27", "#10b981", "#ff5a5f", "#0f172a"],
  },
  {
    name: "nord",
    label: "Nord",
    colors: ["#eceff4", "#5e81ac", "#81a1c1", "#3b4252"],
  },
  {
    name: "sunset",
    label: "Sunset",
    colors: ["#1e293b", "#f5734c", "#ec4899", "#ffffff"],
  },
];

export const LANGUAGES = [
  "English",
  "Hindi",
  "Telugu",
  "Tamil",
  "Marathi",
  "Bengali",
  "Gujarati",
  "Kannada",
  "Malayalam",
  "Punjabi",
  "Odia",
  "Assamese",
  "Urdu",
  "Sanskrit",
  "Konkani",
  "Manipuri",
  "Nepali",
  "Sindhi",
  "Kashmiri",
  "Maithili",
  "Santali",
  "Dogri",
  "Spanish",
  "French",
  "German",
  "Mandarin",
  "Japanese",
  "Korean",
  "Russian",
  "Portuguese",
  "Arabic",
  "Italian",
  "Turkish",
  "Dutch",
  "Indonesian",
  "Vietnamese",
  "Thai",
  "Polish",
  "Ukrainian",
  "Romanian",
  "Greek",
  "Czech",
  "Swedish",
  "Hungarian",
  "Finnish",
  "Danish",
  "Norwegian",
  "Slovak",
  "Bulgarian",
  "Croatian",
  "Serbian",
  "Lithuanian",
  "Slovenian",
  "Latvian",
  "Estonian",
  "Icelandic",
  "Irish",
  "Welsh",
  "Maltese",
  "Albanian",
  "Macedonian",
  "Bosnian",
  "Persian",
  "Hebrew",
  "Swahili",
  "Afrikaans",
  "Zulu",
  "Xhosa",
  "Amharic",
  "Yoruba",
  "Igbo",
  "Hausa",
  "Somali",
  "Malay",
  "Tagalog",
  "Javanese",
  "Sundanese",
  "Burmese",
  "Khmer",
  "Lao",
  "Sinhala",
  "Pashto",
  "Kurdish",
  "Uzbek",
  "Kazakh",
  "Azerbaijani",
  "Georgian",
  "Armenian",
  "Mongolian",
  "Tibetan",
  "Uyghur",
  "Turkmen",
  "Kyrgyz",
  "Tajik",
  "Catalan",
  "Basque",
  "Galician",
  "Luxembourgish",
  "Belarusian",
  "Macedonian",
  "Maori",
  "Samoan",
  "Tongan",
  "Fijian",
  "Hawaiian",
  "Malagasy",
  "Sesotho",
  "Shona",
  "Kinyarwanda",
  "Chichewa",
  "Tigrinya",
  "Oromo",
  "Lingala",
  "Kongo",
  "Wolof",
  "Bambara",
  "Ewe",
  "Twi",
  "Fon",
  "Luganda",
  "Tswana",
  "Tsonga",
  "Venda",
  "Ndebele",
];

export const LANGUAGE_TO_FLAG = {
  english: "gb",
  spanish: "es",
  french: "fr",
  german: "de",
  mandarin: "cn",
  japanese: "jp",
  korean: "kr",
  hindi: "in",
  russian: "ru",
  portuguese: "pt",
  arabic: "sa",
  italian: "it",
  turkish: "tr",
  dutch: "nl",
};

export const LANGUAGE_CODE_MAP = {
  english: "en",
  hindi: "hi",
  telugu: "te",
  tamil: "ta",
  marathi: "mr",
  bengali: "bn",
  gujarati: "gu",
  kannada: "kn",
  malayalam: "ml",
  punjabi: "pa",
  odia: "or",
  assamese: "as",
  urdu: "ur",
  sanskrit: "sa",
  konkani: "kok",
  manipuri: "mni",
  nepali: "ne",
  sindhi: "sd",
  kashmiri: "ks",
  maithili: "mai",
  santali: "sat",
  dogri: "doi",
  spanish: "es",
  french: "fr",
  german: "de",
  mandarin: "zh",
  japanese: "ja",
  korean: "ko",
  russian: "ru",
  portuguese: "pt",
  arabic: "ar",
  italian: "it",
  turkish: "tr",
  dutch: "nl",
  indonesian: "id",
  vietnamese: "vi",
  thai: "th",
  polish: "pl",
  ukrainian: "uk",
  romanian: "ro",
  greek: "el",
  czech: "cs",
  swedish: "sv",
  hungarian: "hu",
  finnish: "fi",
  danish: "da",
  norwegian: "no",
  slovak: "sk",
  bulgarian: "bg",
  croatian: "hr",
  serbian: "sr",
  lithuanian: "lt",
  slovenian: "sl",
  latvian: "lv",
  estonian: "et",
  icelandic: "is",
  irish: "ga",
  welsh: "cy",
  maltese: "mt",
  albanian: "sq",
  macedonian: "mk",
  bosnian: "bs",
  persian: "fa",
  hebrew: "he",
  swahili: "sw",
  afrikaans: "af",
  zulu: "zu",
  xhosa: "xh",
  amharic: "am",
  yoruba: "yo",
  igbo: "ig",
  hausa: "ha",
  somali: "so",
  malay: "ms",
  tagalog: "tl",
  javanese: "jv",
  sundanese: "su",
  burmese: "my",
  khmer: "km",
  lao: "lo",
  sinhala: "si",
  pashto: "ps",
  kurdish: "ku",
  uzbek: "uz",
  kazakh: "kk",
  azerbaijani: "az",
  georgian: "ka",
  armenian: "hy",
  mongolian: "mn",
  tibetan: "bo",
  uyghur: "ug",
  turkmen: "tk",
  kyrgyz: "ky",
  tajik: "tg",
  catalan: "ca",
  basque: "eu",
  galician: "gl",
  luxembourgish: "lb",
  belarusian: "be",
  maori: "mi",
  samoan: "sm",
  tongan: "to",
  fijian: "fj",
  hawaiian: "haw",
  malagasy: "mg",
  sesotho: "st",
  shona: "sn",
  kinyarwanda: "rw",
  chichewa: "ny",
  tigrinya: "ti",
  oromo: "om",
  lingala: "ln",
  kongo: "kg",
  wolof: "wo",
  bambara: "bm",
  ewe: "ee",
  twi: "tw",
  fon: "fon",
  luganda: "lg",
  tswana: "tn",
  tsonga: "ts",
  venda: "ve",
  ndebele: "nd",
};
